### ISSUE TITLE
memdump in words

### ISSUE THREAD

**Issue by maziac** [maziac/DeZog#30]
Hi There i just want to say awesome work on this, I have been using it on the spectrum next, and i was looking to see if the memory dump could be displayed as words rather than just bytes. I can't find the command :( 

Many thanks

Patricia
luckyredfish.com

_Originally posted by @infromthecold in https://github.com/maziac/DeZog/pull/25#issuecomment-702030182_

**Comment by maziac** [comment]
The z80 ist an 8bit Maschine, so what ist your use case here.

If you e.g. just want to lookup an array of defw values you can also simply add the label to the Watch Windows.

**Comment by infromthecold** [comment]
Many thanks for this, yes i know its 8 bit but i have tables of addresses
which are 16 bits so it would make it easier if i could see them as words
and swap the endianness for easy debugging,anyhow i can manage, it's not
like i have to dump things to the screen like we had to in 1983, it's great
having a real debugger.

**Comment by maziac** [comment]
I understand that it can be useful to see the dump as words.
But for that use case shouldn't the watch mentioned above be helpful

**Comment by infromthecold** [comment]
Oh yes, please don't get me wrong it the watches were very handy, I am not
complaining, your debugger is awesome.

If you get around to wanting to add a feature, it would be great if we
could save a memory dump to disk maybe similar to the md command such as
-sd startAddress, howManyBytes, filePathName, this would have been handy
yesterday, as i had hand type (copy and paste was messy) the memory into
excel (so i could see words with the visual endian format) to check my
double linked list was correct, however that's just me.

Anyhow as i say, awesome work, you are already making my life easy.

Many thanks

**Comment by maziac** [comment]
I renamed command "md" to "mv" and added 2 new commands:
"-md address size [dec|hex] [word] [little|big]": Memory dump at 'address' with 'size' bytes. Output is in 'hex' (default) or 'dec'imal. Per default data will be grouped in bytes. But if chosen, words are output. Last argument is the endianess which is little endian by default.
"-ms address size filename": Saves a memory dump to a file. The file is saved to the temp directory.

Please test if it suits your needs.

You find the release here: https://github.com/maziac/DeZog/releases/tag/v1.4.10

**Comment by infromthecold** [comment]
Awesome, thanks that make life easy, all great stuff, i see the memory dump
is now in the debug console and not a window, is this permanent or can we
have the option to have it in a window? Another annoying thing is :- when
you refresh the debug session it creates a new window of where all the
registers are pointing "Memory Dump @HL @DE......"  which is annoying as it
is making two or more versions of the same window and I have to keep
closing it.

Stirling work, please let me know if you need any more tests!

**Comment by maziac** [comment]
I'm currently thinking of adding an option to all all commands to redirect output to a window.
But: you cannot copy text from a window. I haven't found any way to convince vscode to do so. Could be a vscode bug.

Could you enter a new bug for the other issue.

**Comment by maziac** [comment]
Just saw: you can copy with CTRL-C. Only right-mouse is disabled.

**Comment by maziac** [comment]
You can forget about entering a bug. I think I have corrected it here:
https://github.com/maziac/DeZog/releases/tag/v1.4.11

Please let me know if it works.

**Comment by maziac** [comment]
I tried to reach you via email, but maybe the address was wrong...

Have just found your web site and like it very much. A great source of information.

I saw that you have written a feature that includes DeZog as development tool.
(https://luckyredfish.com/coding-for-the-spectrum-next-emulator-cspect/)

In GitHub/DeZog there is a section with links to DeZog tutorials and I would like to add it there if that is OK to you.

**Comment by infromthecold** [comment]
Sorry I have been ill recently and therefore no so much on the emails, by
all means yes please add links

Still not well, many thanks
Patricia

**Comment by maziac** [comment]
Thanks, I will add the link.
And get well soon.

BTW the email address I found on your web site has a problem.
https://luckyredfish.com/doomsday-demo/
This is the error I got:
"A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error. 
Reason:
multiple delivery attempts failed"
